export const FieldTypes = {
  TEXT: "@@FIELD_TYPE/TEXT",
  TEXT_PASSWORD: "@@FIELD_TYPE/TEXT_PASSWORD",
  TEXTAREA: "@@FIELD_TYPE/TEXTAREA",
  NUMBER: "@@FIELD_TYPE/NUMBER",
  SELECT: "@@FIELD_TYPE/SELECT",
  RADIO: "@@FIELD_TYPE/RADIO",
  CHECKBOX: "@@FIELD_TYPE/CHECKBOX",
  SELECT_LIST: "@@FIELD_TYPE/SELECT_LIST",
  FILE: "@@FIELD_TYPE/FILE",
  AUTOCOMPLETE: "@@FIELD_TYPE/AUTOCOMPLETE",
  DATEPICKER: "@@FIELD_TYPE/DATEPICKER",
  RENDER: "@@FIELD_TYPE/RENDER", // only prints out render as is
};

export const DEFAULT_RESPONSE = (response) => {
  return response;
};
